In [ ]:
!git clone https://github.com/mistralai/mistral-src.git

Cloning into 'mistral-src'...
remote: Enumerating objects: 156, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 156 (delta 65), reused 45 (delta 32), pack-reused 69
Receiving objects: 100% (156/156), 373.18 KiB | 7.77 MiB/s, done.
Resolving deltas: 100% (74/74), done.


In [ ]:
!cp -r /content/mistral-src /content/drive/MyDrive/MCQA

In [ ]:
!pip install -q -U transformers
!pip install -q -U accelerate
!pip install -q -U bitsandbytes
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 MB 8.6 MB/s eta 0:00:00


In [ ]:
!pip install xformers
!pip install fire
!pip install sentencepiece
!pip install torch>=2.1.0
!pip install simple-parsing

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 MB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 48.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 51.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 64.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116934 sha256=1eade5bfa9ebad4a2dd2e4b4f3375373ced4388ffc44dd8550bcb5c5832b1f3f
  Stored in directory: /root/.cache/pip/wheels/90/d4/f7/9404e5db0116bd4d43e5666eaa3e70ab53723e1e3ea40c9a95
Successfully built fire
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.4/113.4 kB 3.1 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset
from datasets import DatasetDict

dataset = load_dataset("medmcqa")
dataset.save_to_disk('/content/drive/MyDrive/MCQA/dataset/MedMCQA')

# Train MistralAI

In [ ]:
from pathlib import Path

code_path = "/content/drive/MyDrive/MCQA/mistral-src"  # codebase
#data_path = Path("/dataset_path/Symptom2Disease.csv")  # dataset downloaded from Kaggle
model_path = Path("/content/drive/MyDrive/MCQA/mistral-src/mistral")  # model and tokenizer location

In [ ]:
import csv
import tqdm
import torch
import numpy as np

import sys
sys.path.append(code_path)  # append the path where mistral-src was cloned

from mistral.model import Transformer
from mistral.tokenizer import Tokenizer

In [ ]:
model = Transformer.from_folder(model_path, dtype=torch.bfloat16)
tokenizer = Tokenizer(str(model_path / "tokenizer.model"))

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MCQA/mistral-src/mistral/consolidated.00.pth'

In [ ]:
data = []  # list of (text, label)
with open(data_path, newline='') as csvfile:
    reader = csv.reader(csvfile)
    for i, row in enumerate(reader):
        if i == 0:  # skip csv header
            continue
        data.append((row[2], row[1]))

# label text to label ID
labels = sorted({x[1] for x in data})
txt_to_label = {x: i for i, x in enumerate(labels)}
print(f"Reloaded {len(data)} samples with {len(labels)} labels.")

# integer class for each datapoint
data_class = [txt_to_label[x[1]] for x in data]

In [ ]:
with torch.no_grad():
    featurized_x = []
    # compute an embedding for each sentence
    for i, (x, y) in tqdm.tqdm(enumerate(data)):
        tokens = tokenizer.encode(x, bos=True)
        tensor = torch.tensor(tokens).to(model.device)
        features = model.forward_partial(tensor, [len(tokens)])  # (n_tokens, model_dim)
        featurized_x.append(features.float().mean(0).cpu().detach().numpy())

# concatenate sentence embeddings
X = np.concatenate([x[None] for x in featurized_x], axis=0)  # (n_points, model_dim)

In [ ]:
import sklearn
from sklearn.manifold import TSNE
from matplotlib import pyplot as plt
from matplotlib.cm import rainbow

# This is a sanity check that our data clusters nicely
# map our feature space to 2D, plot it and color it by its labels

reduced = sklearn.manifold.TSNE(n_components=2, random_state=0).fit_transform(X)
plt.scatter(reduced[:, 0], reduced[:, 1], c=data_class, cmap='rainbow')
plt.show()

In [ ]:
# make things reproducible
rng = np.random.default_rng(seed=0)

# shuffle the data
permuted = rng.permutation(len(X))
shuffled_x, shuffled_class = X[permuted], np.array(data_class)[permuted]

# create a train / test split
train_prop = 0.8
n_train = int(len(shuffled_x) * 0.8)
train_x, train_y = shuffled_x[:n_train], shuffled_class[:n_train]
test_x, test_y = shuffled_x[n_train:], shuffled_class[n_train:]

# summary
print(f"Train set : {len(train_x)} samples")
print(f"Test set  : {len(test_x)} samples")

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)
test_x = scaler.transform(test_x)

In [ ]:
from sklearn.linear_model import LogisticRegression

# For a real problem, C should be properly cross validated and the confusion matrix analyzed
clf = LogisticRegression(random_state=0, C=1.0, max_iter=500).fit(train_x, train_y)  # 98.33%

# you can also try the sag algorithm:
# clf = LogisticRegression(random_state=0, C=1.0, max_iter=1000, solver='sag').fit(train_x, train_y)

print(f"Precision: {100*np.mean(clf.predict(test_x) == test_y):.2f}%")

In [ ]:
@torch.no_grad()
def classify(s: str):
    tokens = tokenizer.encode(s, bos=True)
    tensor = torch.tensor(tokens).to(model.device)
    features = model.forward_partial(tensor, [len(tokens)])  # (n_tokens, model_dim)
    embedding = features.float().mean(0).cpu().detach().numpy()
    probas = clf.predict_proba(embedding[None])
    assert probas.shape == (1, len(labels))
    return probas[0]

In [ ]:
sentence = "I have been feeling excessively hungry, even after eating, and have had a stiff neck."
probas = classify(sentence)

for i in np.argsort(probas)[::-1][:5]:
    print(f"{100*probas[i]:6.2f}%  {labels[i]}")

In [ ]:
model.args.max_batch_size = len(labels)

test_data = [data[i] for i in permuted[n_train:]]

good = []

with torch.no_grad():

    for i, (symptom, disease) in tqdm.tqdm(enumerate(test_data)):

        # given an input, predict the probability of each output (one output corresponds to one label)
        input_ids, seq_lengths, output_lengths = [], [], []
        for label in labels:
            prefix = f"Symptoms: {symptom}\nDisease:"
            tokens = tokenizer.encode(f"{prefix} {label}", bos=True)
            input_ids.extend(tokens)
            seq_lengths.append(len(tokens))
            output_lengths.append(len(tokens) - len(tokenizer.encode(prefix, bos=True)))
        tensor = torch.tensor(input_ids).to(model.device)
        logprobs = torch.log_softmax(model.forward(tensor, seq_lengths), dim=-1)  # sum_slens * vocab_size

        # select logprobs for each output
        offset = 0
        avg_logprobs = []
        for slen, output_len in zip(seq_lengths, output_lengths):
            output_tokens = input_ids[offset + slen - output_len:offset + slen]
            output_logprobs = torch.gather(
                logprobs[offset + slen - output_len - 1:offset + slen - 1],
                dim=1,
                index=torch.tensor(output_tokens).to(model.device)[:, None],
            ).mean().item()
            avg_logprobs.append(output_logprobs)
            offset += slen

        good.append(np.argmax(avg_logprobs) == txt_to_label[disease])

print(f"Accuracy: {100 * np.mean(good):.2f}%")

# Huggingface




In [1]:
!pip install -q transformers==4.34.0 datasets==2.14.5 accelerate==0.23.0 evaluate==0.4.1 peft==0.5.0
!pip install bitsandbytes
!pip install sentencepiece
!pip install transformers bitsandbytes accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 51.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 53.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.1/258.1 kB 32.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.6/85.6 kB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 105.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 19.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 34.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 MB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 18.1 MB/s eta 0:00:00


In [2]:
pip install -U transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 57.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.3/330.3 kB 37.1 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of tokenizers to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 101.0 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.14.1
    Uninstalling tokenizers-0.14.1:
      Successfully uninstalled tokenizers-0.14.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.34.0
    Uninstalling transformers-4.34.0:
      Successfully uninstalled transformers-4.34.0


In [ ]:
!pip install --no-cache-dir transformers sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 27.3 MB/s eta 0:00:00


In [ ]:
!pip install sentencepiece

In [ ]:
!pip install transformers[sentencepiece]

In [ ]:
!pip install sacremoses

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 880.6/880.6 kB 14.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895241 sha256=bedcadd7c1189e78e44a5b890abc02e77898e337e9d0a84037aeb3ba325a3897
  Stored in directory: /root/.cache/pip/wheels/00/24/97/a2ea5324f36bc626e1ea0267f33db6aa80d157ee977e9e42fb
Successfully built sacremoses


In [ ]:
from datasets import load_dataset
from datasets import DatasetDict

dataset = load_dataset("medmcqa") # medalpaca/medical_meadow_medqa, pubmed_qa, cais/mmlu

In [ ]:
raw_dataset = {
    'train': dataset['train'],
    'valid': dataset['validation']
}
raw_dataset = DatasetDict(raw_dataset)
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 182822
    })
    valid: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 4183
    })
})

In [ ]:
raw_dataset_t=raw_dataset['train'].train_test_split(test_size=0.5)
raw_dataset_v=raw_dataset['valid'].train_test_split(test_size=0.5)

In [ ]:
raw_dataset = {
    'train': raw_dataset_t['train'],
    'valid': raw_dataset_v['train']
}
raw_dataset = DatasetDict(raw_dataset)
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 91411
    })
    valid: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 2091
    })
})

In [ ]:
def generate_prompt(x):
    cop = 'Nothing'
    if x['cop'] == 0:
        cop = x['opa']
    elif x['cop'] == 1:
        cop = x['opb']
    elif x['cop'] == 2:
        cop = x['opc']
    elif x['cop'] == 3:
        cop = x['opd']
    question = '{}\nOptions:\n1. {}\n2. {}\n3. {}\n4. {}\n'.format(x['question'], x['opa'], x['opb'], x['opc'], x['opd'])
    answer = cop
    context = x['exp']
    prompt = f"""2
    <s>### Context:
    {context}
    ### Question:
    {question}
    [INST] Solve this post graduate medical entrance exam MCQ and provide the correct option. [/INST]
    ### Answer:
    {answer}</s>"""

    return prompt

In [5]:
import torch
from transformers import GPTQConfig, BitsAndBytesConfig, AutoTokenizer, AutoModelForCausalLM, AutoModelForSeq2SeqLM, AutoModelForQuestionAnswering , BioGptTokenizer, BioGptForCausalLM,GPT2Tokenizer, GPT2Model
from peft import get_peft_model, LoraConfig, TaskType, prepare_model_for_kbit_training

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)
model_name = 'mistralai/Mistral-7B-Instruct-v0.2' #microsoft/BioGPT-Large-PubMedQA

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.unk_token
tokenizer.pad_token_id =  tokenizer.unk_token_id
tokenizer.padding_side = 'left'


quantization_config_loading = GPTQConfig(
                                bits=4,
                                disable_exllama=True,
                                tokenizer=tokenizer
                            )
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    use_cache=False,
    device_map="auto"
    )

peft_config = LoraConfig(
        r=64,
        task_type= "CAUSAL_LM",
        lora_alpha=16,
        lora_dropout=0.1,
        target_modules=[ "q_proj",
                        "k_proj",
                         "v_proj",
                         "o_proj",
                         "gate_proj",
                         "up_proj",
                         "down_proj",
                         "lm_head",
        ],
        bias="none"
    )

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

Using `disable_exllama` is deprecated and will be removed in version 4.37. Use `use_exllama` instead and specify the version with `exllama_config`.The value of `use_exllama` will be overwritten by `disable_exllama` passed in `GPTQConfig` or stored in your config file.


config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
!pip install transformers[torch]
!pip install accelerate -U
!pip install trl

In [ ]:
import transformers
from transformers import DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments, TrainingArguments
from trl import SFTTrainer

In [ ]:
import numpy as np
import evaluate
from transformers import EvalPrediction

label2id = {
    'A': '0',
    'B': '1',
    'C': '2',
    'D': '3',
    'E': '4'
}

def postprocess_text(predictions, labels):
    predictions = [prediction.strip() for prediction in predictions]
    labels = [label2id[label.strip()] for label in labels]

    for idx in range(len(predictions)):
        if predictions[idx] in label2id:
           predictions[idx] = label2id[predictions[idx]]
        else:
            predictions[idx] = '-100'
    return predictions, labels

def load_metric(metric_name):
    if metric_name == "accuracy":
        return evaluate.load("accuracy")
    elif metric_name == "f1":
        return evaluate.load("f1")

def seq2seq_compute_metrics(tokenizer, metric):
    def compute_metrics(eval_pred: EvalPrediction):
        nonlocal tokenizer, metric
        predictions, labels = eval_pred
        if isinstance(predictions, tuple):
            predictions = predictions[0]

        predictions = tokenizer.batch_decode(predictions, skip_special_tokens=True)
        # Replace -100 in the labels as we can't decode them.
        labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
        labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
        predictions, labels = postprocess_text(predictions, labels)
        result = metric.compute(predictions=predictions, references=labels)
        return result
    return compute_metrics
metric = evaluate.load("accuracy")
compute_metrics = seq2seq_compute_metrics(tokenizer, metric)

In [ ]:
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return metric.compute(predictions=predictions, references=labels)

In [ ]:
training_arguments = TrainingArguments(
                            output_dir="model",
                            per_device_train_batch_size=8,
                            per_device_eval_batch_size=32,
                            gradient_accumulation_steps=1,
                            optim="paged_adamw_32bit",
                            learning_rate=2e-4,
                            lr_scheduler_type="cosine",
                            save_strategy="steps",
                            evaluation_strategy='steps',
                            logging_steps=400,
                            save_steps=400,
                            num_train_epochs=1,
                            eval_steps = 100,
                            max_steps=2000,
                            fp16=True,
                            #metric_for_best_model='accuracy',
                            load_best_model_at_end=True,
                            save_total_limit=2,
                            #push_to_hub=True
                        )


In [ ]:
trainer = SFTTrainer(
            model=model,
            train_dataset=raw_dataset['train'],
            eval_dataset = raw_dataset['valid'],
            peft_config=peft_config,
            formatting_func =generate_prompt,
            # dataset_text_field ='input_ids',
            args=training_arguments,
            tokenizer=tokenizer,
            #compute_metrics= compute_metrics,
            packing=True,
            max_seq_length=512
    )

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:290: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:310: UserWarning: You passed `packing=True` to the SFTTrainer, and you are training your model with `max_steps` strategy. The dataset will be iterated until the `max_steps` are reached.
  warnings.warn(


In [ ]:
trainer.train()

You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


KeyboardInterrupt: 

In [ ]:
trainer.save_model('/content/drive/MyDrive/MCQA')

In [ ]:
# Save our tokenizer and create model card
tokenizer.save_pretrained('model')
trainer.save_model()
trainer.create_model_card()
# Push the results to the hub
#trainer.push_to_hub()


In [6]:
from datasets import load_dataset
from datasets import DatasetDict

dataset = load_dataset("medmcqa") # medalpaca/medical_meadow_medqa, pubmed_qa, cais/mmlu

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/182822 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6150 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4183 [00:00<?, ? examples/s]

In [7]:
raw_dataset = {
    'train': dataset['train'],
    'valid': dataset['validation']
}
raw_dataset = DatasetDict(raw_dataset)
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 182822
    })
    valid: Dataset({
        features: ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name'],
        num_rows: 4183
    })
})

In [8]:
import pandas as pd

val_data_df = pd.DataFrame(raw_dataset['valid'])

In [9]:
from functools import partial
def generate_test_prompt(x):
    question = '{}\nOptions:\n1. {}\n2. {}\n3. {}\n4. {}\n'.format(x['question'], x['opa'], x['opb'], x['opc'], x['opd'])
    prompt = f"""
    Question:
    {question}
    [INST] Solve this post graduate medical entrance exam MCQ and answer correctly. [/INST]
    Answer: """
    return prompt


In [10]:
val_data_df['text'] = val_data_df.apply(lambda x: generate_test_prompt(x), axis=1)

In [11]:
from peft import AutoPeftModelForCausalLM
from transformers import GenerationConfig
from transformers import AutoTokenizer
import torch
import tqdm
import json



In [ ]:
model_id = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoPeftModelForCausalLM.from_pretrained(
    model_id,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map="cuda")

generation_config = GenerationConfig(
    do_sample=True,
    top_k=1,
    temperature=0.1,
    max_new_tokens=25,
    pad_token_id=tokenizer.pad_token_id
)

In [12]:
generation_config = GenerationConfig(
    do_sample=True,
    top_k=1,
    temperature=0.1,
    max_new_tokens=25,
    pad_token_id=tokenizer.pad_token_id
)

In [13]:
def solve_question(question_prompt):
    inputs = tokenizer(question_prompt, return_tensors="pt", padding=True, truncation=True).to("cuda")
    outputs = model.generate(**inputs, generation_config=generation_config)
    answer = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    return answer

all_answers = []
import re
val_data_prompts = list(val_data_df['text'])
for i in tqdm.tqdm(range(0, len(val_data_prompts), 16)):
    question_prompts = val_data_prompts[i:i+16]
    ans = solve_question(question_prompts)
    ans_option = []
    for text in ans:
        ans_option.append(re.search(r'Answer: \s*(.*)', text).group(1))

    all_answers.extend(ans_option)

100%|██████████| 262/262 [1:44:22<00:00, 23.90s/it]


In [ ]:
all_answers

In [ ]:
correct_answers

In [ ]:
len(correct_answers)

4183

In [ ]:
val_data_df['cop'][100]

0

In [14]:
import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

In [15]:
!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')




     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=02d602e4d41172e814ca5dab0d1a89468059a3751a3e95522da995192f02a80b
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [16]:
correct_answers = []
for i in range(len(val_data_df)):
    if (val_data_df['cop'][i]+1) == 1:
        correct_answers.append(val_data_df['opa'][i])
    elif (val_data_df['cop'][i]+1) == 2:
        correct_answers.append(val_data_df['opb'][i])
    elif (val_data_df['cop'][i]+1) == 3:
        correct_answers.append(val_data_df['opc'][i])
    elif (val_data_df['cop'][i]+1) == 4:
        correct_answers.append(val_data_df['opd'][i])


In [17]:
correct_count=0
list_sim=[]
#Compute embedding for both lists
for i in range(len(val_data_df)):
  embedding_1= model.encode(correct_answers[i], convert_to_tensor=True)
  embedding_2 = model.encode(all_answers[i], convert_to_tensor=True)
  if util.pytorch_cos_sim(embedding_1, embedding_2) >=0.6:
    correct_count+=1
    list_sim.append(util.pytorch_cos_sim(embedding_1, embedding_2))
correct_count/len(val_data_df)

0.467846043509443

In [18]:
list_sim

[tensor([[0.6019]], device='cuda:0'),
 tensor([[1.]], device='cuda:0'),
 tensor([[0.9370]], device='cuda:0'),
 tensor([[0.9524]], device='cuda:0'),
 tensor([[0.9444]], device='cuda:0'),
 tensor([[0.9453]], device='cuda:0'),
 tensor([[0.8640]], device='cuda:0'),
 tensor([[0.9766]], device='cuda:0'),
 tensor([[0.8482]], device='cuda:0'),
 tensor([[0.7777]], device='cuda:0'),
 tensor([[0.9069]], device='cuda:0'),
 tensor([[0.8724]], device='cuda:0'),
 tensor([[0.9061]], device='cuda:0'),
 tensor([[0.6069]], device='cuda:0'),
 tensor([[0.8146]], device='cuda:0'),
 tensor([[0.9391]], device='cuda:0'),
 tensor([[0.9162]], device='cuda:0'),
 tensor([[1.]], device='cuda:0'),
 tensor([[0.6478]], device='cuda:0'),
 tensor([[1.]], device='cuda:0'),
 tensor([[0.8921]], device='cuda:0'),
 tensor([[0.7554]], device='cuda:0'),
 tensor([[0.8051]], device='cuda:0'),
 tensor([[0.9072]], device='cuda:0'),
 tensor([[0.8924]], device='cuda:0'),
 tensor([[0.8147]], device='cuda:0'),
 tensor([[0.9521]], devi